development:
  adapter: postgresql
  encoding: unicode
  database: siged20_development
  pool: 5
  host: localhost
  username: postgres
  password: malocasoft

production:
  adapter: postgresql
  encoding: unicode
  database: siged
  pool: 5
  host: ssh.siged.seed.ap.gov.br
  username: postgres
#  password: malocasoft

