# -*- encoding : utf-8 -*-
source 'http://rubygems.org'
ruby '2.1.1'
gem 'rails', '3.2.22'
gem 'iconv'
gem 'thor'
gem 'statistics'
# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem "odf-report"
gem "paperclip"#,:path =>'vendor/cache/git/paperclip'#:git=>"git://github.com/thoughtbot/paperclip"
gem 'pg'
gem 'kaminari'
gem 'brazilian-rails', '3.1.0'
#gem 'brI18n'
gem 'will_paginate'
gem 'bootstrap-will_paginate', '0.0.10'
gem 'devise'
gem 'carrierwave'
gem 'calendar_date_select'
gem 'carrierwave-postgresql'
gem 'mini_magick'
gem 'chunky_png'
gem 'cancan'
gem 'wicked_pdf'
gem 'liquid'
gem 'ransack'
gem "wkhtmltopdf", "~> 0.1.2"
gem 'barby'
#gem 'rmagick', '2.13.3'
gem 'railroady'
gem "secure_headers", require: 'secure_headers'
#gem 'axlsx'
#gem 'silent-postgres'

gem 'serenity-odt','0.2.0'
gem 'state_machine'
#gem 'messaging', :git=> 'git://github.com/frodefi/rails-messaging.git'
#gem 'mailboxer'
#gem 'prototype_legacy_helper', '0.0.0', :git => 'https://github.com/rails/prototype_legacy_helper.git'
gem "validates_existence", ">= 0.4"
gem 'rufus-scheduler'
gem 'ruport'
# Use unicorn as the web server
# gem 'unicorn'
gem 'friendly_id'
gem "cocoon"
gem 'rails-jquery-autocomplete'
gem 'puma', '2.7.1'
gem 'thin'
gem 'validates_timeliness','3.0.14'
gem 'nested_form'
gem 'combine_pdf'
gem 'ajax_pagination'
gem 'jquery-rails'
gem "jquery-historyjs"
gem 'twitter-bootstrap-rails'
gem 'simple_form'
gem 'less-rails'
gem 'therubyracer'
gem 'simple_enum', '1.6.9'
#gem 'activerecord-session_store'
gem "iconv"
gem 'devise-bootstrap-views'
gem 'wicked'
gem 'workbook'
gem 'select2-rails', '~> 4.0', '>= 4.0.1.1'
# gem 'best_in_place', '~> 3.0.1'
