development:
  adapter: postgresql
  encoding: unicode
  database: siged20_development
  pool: 5
  host: localhost
  username: postgres
  password: malocasoft

production:
  adapter: postgresql
  encoding: unicode
  database: siged20_development
  pool: 5
  host: localhost
  username: postgres
  password: malocasoft

